### PR TITLE
Compatibility-Fixes for Django 4

### PR DESCRIPTION
**Pull request by juliushacker**
I'd like to contribute these two fixes needed to be compatible with django 4.

### CODE REVIEW

**Comment by praveen-db2** [comment]
Appreciate your contribution, I will consider this change in my next delivery, which I am taking up shortly.

**Comment by 0x2ec** [comment]
See also #81 - I pushed that PR for Django 4 support. But I think eb70d062523b426cdbc0f8de61e8ccee00b9e1cb is worthwhile including, I didn't make any changes like that.

**Review by praveen-db2 — APPROVED** [review]

**Comment by Janani26priya** [comment]
@praveen-db2 I'd like to ask if you could deliver this fix as a patch at least, as our team is unable to use ibm_db_django version 1.5.2.0 in our ci/cd pipeline due to the following error. I tried using previous versions but no luck with that. 

```
error in ibm_db_django setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; .* suffix can only be used with `==` or `!=` operators
          django>=3.2.*
```

**Comment by praveen-db2** [comment]
@Janani26priya I am almost ready with developments of supporting Django 4.2. Shortly in another week or two I will be delivering new release.

**Pull request merged**
